# stocks api
poke:
  api:
    pokemon:
      fqdn: https://pokeapi.co/api/v2/pokemon/
  jwt:
    jwtExpirationMs:
      86400000
    secret:
      "%WSKaJDmKs8L7sbtominmrteh5hkoitrgjrtbiuruhbmrjtg5ijgrvofjbrtjnynbjgbekgjhokthjopikgjbiubtnoeruyhgothoptb"
      
    
spring:
  data:
    mysql:
      database: userInfo
      table: credentials
      host: localhost
      port: 3306
      
